# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-20 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190520_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.DateField(),
        ),
    ]
